# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Zabawy na Wodzie
email: zabawynawodzie@gmail.com
phone: +48 555 997 666
address_1: ul. Dąbkowskiego 51 lokal 3b
address_2: 42-202 Nowy Sącz
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
brand-color: ff8a48

logo:
  - file: baseline-verified_user-24px.svg
    alt: logo-01

  - file: baseline-stars-24px.svg
    alt: logo-01

social:
  - social-media: facebook
    social-url: #
    icon: fab fa-facebook-square

  - social-media: instagram
    social-url: #
    icon: fab fa-instagram

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

nav:
  - title: O nas
    url: o-nas

copyrights: Zabawy na Wodzie
authors: www.edwingrafik.com
authors-external-url: https://edwingrafik.com/

header_pages:
 - o-nas.html

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

images:
  - file:
    alt:


hero:
  - file: steven-welch-124749-unsplash.jpg
    title: Wakeboard
    desc: Wakeboard Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.
    filter: yellow--red
    id: wakeboard

  - file: caleb-vandenheuvel-407861-unsplash.jpg
    title: Narty wodne
    desc: Narty wodne Lorem ipsum dolor
    filter:
    id: water-ski

  - file: 33944106_2116176085327162_1685665829208719360_o.jpg
    title: Koło
    desc: Koło Lorem ipsum dolor
    filter:
    id: tubbing

  - file: IMG_20150801_121529.jpg
    title: Banan
    desc: Banan Lorem ipsum dolor
    filter:
    id: banana

  - file: kolo11.jpg
    title: Przejażdżki motorowką
    desc: Przejażdżki motorowką Lorem ipsum dolor
    filter:
    id: motorboat
