baseurl: "" # the subpath of your site, e.g. /blog
url: "vibrant-rosalind-6163f5.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

logo:
  - file: logo-zabawy-na-wodzie.svg
    alt: logo-zabawy-na-wodzie

social:
  - social-media: facebook
    social-url: #
    icon: fab fa-facebook-square

  - social-media: instagram
    social-url: #
    icon: fab fa-instagram

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compressed

compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
  envs: []

copyrights: Zabawy na Wodzie
authors: www.edwingrafik.com
authors-external-url: https://edwingrafik.com/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  subpages:
    output: true

  pricing:
    output: true

  offer:
    output: true

  contact:
    output: true

  disciplines:
    output: true

motorboat:
  - file: motorowka-P5311370.jpg
    alt:
    caption: Moto 1

  - file: motorowka-P5311379.jpg
    alt:
    caption: Moto 2

  - file: motorowka-P5311393.jpg
    alt:
    caption: Moto 3

  - file: motorowka-P5311416.jpg
    alt:
    caption: Moto 4

  - file: motorowka-P6031609.jpg
    alt:
    caption: Moto 5

  - file: motorowka-P6031613.jpg
    alt:
    caption: Moto 6
